Repository f-lab-edu/momukji-services, pull requests merged in 2022-06, with the labels that each got.

#9 프로젝트 기본 세팅
  .gitignore
  .vscode/settings.json
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kr/flab/momukji/MomukjiApplication.java
  src/main/java/kr/flab/momukji/config/JwtSecurityConfig.java
  src/main/java/kr/flab/momukji/config/SecurityConfig.java
  src/main/java/kr/flab/momukji/controller/AuthController.java
  src/main/java/kr/flab/momukji/controller/UserController.java
  src/main/java/kr/flab/momukji/dto/AuthorityDto.java
  src/main/java/kr/flab/momukji/dto/LoginDto.java
  src/main/java/kr/flab/momukji/dto/TokenDto.java
  src/main/java/kr/flab/momukji/dto/UserDto.java
  src/main/java/kr/flab/momukji/entity/Authority.java
  src/main/java/kr/flab/momukji/entity/User.java
  src/main/java/kr/flab/momukji/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/flab/momukji/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/kr/flab/momukji/jwt/JwtFilter.java
  src/main/java/kr/flab/momukji/jwt/TokenProvider.java
  src/main/java/kr/flab/momukji/repository/UserRepository.java
  src/main/java/kr/flab/momukji/service/CustomUserDetailsService.java
  src/main/java/kr/flab/momukji/service/UserService.java
  src/main/java/kr/flab/momukji/util/SecurityUtil.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/kr/flab/momukji/MomukjiApplicationTests.java
Labels: enhancement

#14 Customer - 주문하기
  .vscode/settings.json
  naver-checkstyle-rules.xml
  src/main/java/kr/flab/momukji/controller/AuthController.java
  src/main/java/kr/flab/momukji/controller/CustomerController.java
  src/main/java/kr/flab/momukji/controller/UserController.java
  src/main/java/kr/flab/momukji/dto/request/AuthorityDto.java
  src/main/java/kr/flab/momukji/dto/request/LoginDto.java
  src/main/java/kr/flab/momukji/dto/request/OrderDto.java
  src/main/java/kr/flab/momukji/dto/request/UserDto.java
  src/main/java/kr/flab/momukji/dto/response/TokenDto.java
  src/main/java/kr/flab/momukji/dto/response/common/CommonResponse.java
  src/main/java/kr/flab/momukji/dto/response/common/ResultCode.java
  src/main/java/kr/flab/momukji/entity/Category.java
  src/main/java/kr/flab/momukji/entity/Order.java
  src/main/java/kr/flab/momukji/entity/Product.java
  src/main/java/kr/flab/momukji/entity/Region.java
  src/main/java/kr/flab/momukji/entity/Rider.java
  src/main/java/kr/flab/momukji/entity/Store.java
  src/main/java/kr/flab/momukji/entity/StoreInfo.java
  src/main/java/kr/flab/momukji/entity/User.java
  src/main/java/kr/flab/momukji/repository/CategoryRepository.java
  src/main/java/kr/flab/momukji/repository/OrderRepository.java
  src/main/java/kr/flab/momukji/repository/ProductRepository.java
  src/main/java/kr/flab/momukji/repository/RegionRepository.java
  src/main/java/kr/flab/momukji/repository/StoreRepository.java
  src/main/java/kr/flab/momukji/service/OrderService.java
  src/main/java/kr/flab/momukji/service/ProductService.java
  src/main/java/kr/flab/momukji/service/StoreService.java
  src/main/java/kr/flab/momukji/service/UserService.java
  src/main/resources/application.yml
  src/test/java/kr/flab/momukji/repository/RepositoryTests.java
Labels: enhancement

#15 Feat-Rider 배차 접수하기
  src/main/java/kr/flab/momukji/controller/RiderController.java
  src/main/java/kr/flab/momukji/dto/request/AcceptRiderDto.java
  src/main/java/kr/flab/momukji/entity/Order.java
  src/main/java/kr/flab/momukji/entity/User.java
  src/main/java/kr/flab/momukji/repository/RiderRepository.java
  src/main/java/kr/flab/momukji/service/OrderService.java
  src/main/java/kr/flab/momukji/service/RiderService.java
Labels: enhancement

#19 feat: Swagger 세팅
  build.gradle
  src/main/java/kr/flab/momukji/config/SecurityConfig.java
  src/main/java/kr/flab/momukji/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: enhancement

#20 data.sql에 테이블 데이터 좀 더 넣어서 로컬 테스트 쉽게 하기
  src/main/java/kr/flab/momukji/entity/Order.java
  src/main/java/kr/flab/momukji/service/OrderService.java
  src/main/resources/data.sql
Labels: enhancement

#21 fix: OrderRepository findById JPA N+1 이슈 해결
  src/main/java/kr/flab/momukji/repository/OrderRepository.java
Labels: bug

#25 feat: 픽업완료하기
  src/main/java/kr/flab/momukji/controller/RiderController.java
  src/main/java/kr/flab/momukji/dto/request/RiderDto.java
  src/main/java/kr/flab/momukji/repository/OrderRepository.java
  src/main/java/kr/flab/momukji/service/OrderService.java
  src/main/java/kr/flab/momukji/service/RiderService.java
Labels: bug, enhancement

#22 Store - 주문 승인하기
  src/main/java/kr/flab/momukji/controller/StoreController.java
  src/main/java/kr/flab/momukji/dto/request/AcceptOrderDto.java
  src/main/java/kr/flab/momukji/dto/response/common/ResultCode.java
  src/main/java/kr/flab/momukji/service/OrderService.java
  src/main/java/kr/flab/momukji/service/StoreService.java
Labels: enhancement

#23 Store - 배차 요청하기
  src/main/java/kr/flab/momukji/controller/StoreController.java
  src/main/java/kr/flab/momukji/dto/request/RequestRiderDto.java
  src/main/java/kr/flab/momukji/service/OrderService.java
Labels: enhancement

#29 자동 빌드/배포 환경 구축
  .github/workflows/cicd.yml
  Dockerfile
  build.gradle
  src/test/resources/application.yml
Labels: bug, enhancement
